version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && gunicorn infra.django.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"

volumes:
  postgres_data:
